### ISSUE TITLE
Trabajo tablas de verdad

### ISSUE THREAD

**Issue by Felix-Angel** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-equipo-mayra-diego-daniel-felix#1]
[TABLAS DE VERDAD_EQUIPO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-equipo-mayra-diego-daniel-felix/files/13289448/TABLAS.DE.VERDAD_EQUIPO.pdf)

**Comment by elisa1223** [comment]
Portada: 25%
Procedimiento: 25%
Figuras,ilustraciones y fotografias: 25%
Resultados y conclusiones: 25%

Calificación final: 20/20
Evaluado por el equipo de Elisa.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
